version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etherflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5454:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: ./wait_for_db.sh poetry run hypercorn app.main:app --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/etherflow
      INFURA_API_KEY: your_infura_api_key

  alembic:
    build:
      context: .
      dockerfile: Dockerfile.alembic
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/etherflow
    volumes:
      - .:/app

  celery:
    build: .
    command: celery -A app.celery.config.celery_app worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/etherflow
      INFURA_API_KEY: your_infura_api_key

volumes:
  postgres_data:
