version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etherflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5454:5432"

  web:
    build: .
    command: poetry run hypercorn app.main:app --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/etherflow

  alembic:
    build:
      context: .
      dockerfile: Dockerfile.alembic
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/etherflow
    volumes:
      - .:/app

volumes:
  postgres_data:
