"""edit type

Revision ID: 3be82fc52981
Revises: 4b4bc59a73b1
Create Date: 2024-08-11 19:00:59.679064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be82fc52981'
down_revision: Union[str, None] = '4b4bc59a73b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_type', sa.String(), nullable=True))
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###
