"""Updated Transaction model

Revision ID: 4b4bc59a73b1
Revises: 888443fcac6b
Create Date: 2024-08-11 18:33:03.119408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4bc59a73b1'
down_revision: Union[str, None] = '888443fcac6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('type', sa.String(), nullable=True))
    op.create_index('ix_transactions_time', 'transactions', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_time', table_name='transactions')
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###
