"""Initial migration

Revision ID: 5a957ee8b020
Revises: 
Create Date: 2024-08-08 10:41:07.784700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a957ee8b020'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_block_number', table_name='transactions')
    op.drop_index('ix_transactions_from_address', table_name='transactions')
    op.drop_index('ix_transactions_id', table_name='transactions')
    op.drop_index('ix_transactions_to_address', table_name='transactions')
    op.drop_index('ix_transactions_tx_hash', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tx_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('block_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('to_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gas_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gas_price_wei', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    op.create_index('ix_transactions_tx_hash', 'transactions', ['tx_hash'], unique=True)
    op.create_index('ix_transactions_to_address', 'transactions', ['to_address'], unique=False)
    op.create_index('ix_transactions_id', 'transactions', ['id'], unique=False)
    op.create_index('ix_transactions_from_address', 'transactions', ['from_address'], unique=False)
    op.create_index('ix_transactions_block_number', 'transactions', ['block_number'], unique=False)
    # ### end Alembic commands ###
